# List of Indian Stock Market (NSE) symbols

# NIFTY 50 Symbols
NIFTY50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "HINDUNILVR.NS", "LT.NS",
    "BAJFINANCE.NS", "HCLTECH.NS", "MARUTI.NS", "SUNPHARMA.NS", "TATAMOTORS.NS",
    "ASIANPAINT.NS", "M&M.NS", "NTPC.NS", "TITAN.NS", "KOTAKBANK.NS",
    "ONGC.NS", "COALINDIA.NS", "AXISBANK.NS", "POWERGRID.NS", "ADANIENT.NS",
    "BAJAJFINSV.NS", "TATASTEEL.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "JSWSTEEL.NS",
    "WIPRO.NS", "GRASIM.NS", "ADANIPORTS.NS", "HINDALCO.NS", "TECHM.NS",
    "APOLLOHOSP.NS", "DIVISLAB.NS", "CIPLA.NS", "HEROMOTOCO.NS", "EICHERMOT.NS",
    "BAJAJ-AUTO.NS", "BRITANNIA.NS", "LTIM.NS", "INDUSINDBK.NS", "HDFCLIFE.NS",
    "DRREDDY.NS", "TATACONSUM.NS", "SBILIFE.NS", "BPCL.NS", "UPL.NS"
]

# NIFTY 100 Symbols (Nifty 50 + Next 50)
NEXT50 = [
    "HAL.NS", "BEL.NS", "TVSMOTOR.NS", "PFC.NS", "RECLTD.NS", "IRFC.NS",
    "CHOLAFIN.NS", "PNB.NS", "ABB.NS", "BANKBARODA.NS", "SHREECEM.NS",
    "GODREJCP.NS", "TRENT.NS", "DLF.NS", "VBL.NS", "SIEMENS.NS",
    "HAVELLS.NS", "AMBUJACEM.NS", "SRF.NS", "BAJAJHLDNG.NS",
    "PIDILITIND.NS", "MUTHOOTFIN.NS", "PETRONET.NS", "ICICIPRULI.NS",
    "BOSCHLTD.NS", "NAUKRI.NS", "BERGEPAINT.NS", "TORNTPHARM.NS",
    "DABUR.NS", "COLPAL.NS", "TATAPOWER.NS", "MARICO.NS", "CANBK.NS",
    "VEDL.NS", "LUPIN.NS", "BANDHANBNK.NS", "PAGEIND.NS", "MCDOWELL-N.NS",
    "SBICARD.NS", "JUBLFOOD.NS", "AUROPHARMA.NS", "ZEE.NS", "PGHH.NS",
    "INDIGO.NS", "CONCOR.NS", "BIOCON.NS", "OBEROIRLTY.NS", "IDFCFIRSTB.NS",
    "LICI.NS", "ADANIGREEN.NS"
]
NIFTY100 = NIFTY50 + NEXT50

# NIFTY 200 list
NIFTY200_EXTRA = [
    "AUBANK.NS", "NMDC.NS", "FEDERALBNK.NS", "VOLTAS.NS",
    "ESCORTS.NS", "MFSL.NS", "CROMPTON.NS", "MOTHERSON.NS",
    "SUPREMEIND.NS", "TIINDIA.NS", "KAJARIACER.NS", "POLYCAB.NS",
    "GMRINFRA.NS", "CUMMINSIND.NS", "GLAXO.NS", "GODREJPROP.NS",
    "BALKRISIND.NS", "DEEPAKNTR.NS", "ASTRAL.NS", "HONAUT.NS",
    "PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS", "L&TFH.NS",
    "KPITTECH.NS", "TATAELXSI.NS", "QUESS.NS", "ZYDUSLIFE.NS",
    "ALKEM.NS", "IPCALAB.NS", "SUNTV.NS", "PVRINOX.NS",
    "BRIGADE.NS", "SOBHA.NS", "PRESTIGE.NS", "PHOENIXLTD.NS",
    "GLENMARK.NS", "NATCOPHARM.NS", "LAURUSLABS.NS", "GRANULES.NS",
    "ATUL.NS", "PIIND.NS", "FLUOROCHEM.NS", "FINEORG.NS",
    "JINDALSTEL.NS", "SAIL.NS", "NATIONALUM.NS", "MOIL.NS",
    "ACC.NS", "RAMCOCEM.NS", "HEIDELBERG.NS", "INDIACEM.NS",
    "BLUEDART.NS", "MAHINDCIE.NS", "SUNDRMFAST.NS", "EXIDEIND.NS",
    "APOLLOTYRE.NS", "MRF.NS", "CEATLTD.NS", "BALKRISIND.NS",
    "WHIRLPOOL.NS", "BLUESTARCO.NS", "SYMPHONY.NS", "BATAINDIA.NS",
    "RELAXO.NS", "CAMPUS.NS", "VGUARD.NS", "RAJESHEXPO.NS",
    "WESTLIFE.NS", "BURGER-KING.NS", "DEVYANI.NS", "SAPPHIRE.NS",
    "TORNTPOWER.NS", "JPPOWER.NS", "NLCINDIA.NS", "SJVN.NS",
    "IRB.NS", "KNRCON.NS", "PNCINFRA.NS", "SADBHAV.NS",
    "ZOMATO.NS", "PAYTM.NS", "NYKAA.NS", "POLICYBZR.NS",
    "DELHIVERY.NS", "CARTRADE.NS", "EASEMYTRIP.NS", "IRCTC.NS",
    "RAILTEL.NS", "RVNL.NS", "ENGINERSIN.NS", "NBCC.NS",
    "MANAPPURAM.NS", "CREDITACC.NS", "UJJIVAN.NS", "EQUITASBNK.NS",
    "ABCAPITAL.NS", "LICSGFIN.NS", "CANFINHOME.NS", "REPCO.NS",
    "KFINTECH.NS", "CAMS.NS", "CDSL.NS", "BSE.NS"
]
NIFTY200 = NIFTY100 + NIFTY200_EXTRA
